<?php

namespace App\Tests;

use PHPUnit\Framework\TestCase;
use App\Task1\ModChecker;

class ModCheckerTest extends TestCase
{
    private ?ModChecker $modChecker = null;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->modChecker = new ModChecker();

    }

    /** @dataProvider getCorrectData */
    public function testCheckReturnedValueByCorrectdata(int $number, string|int $returnedValue): void {
        $this->assertEquals($returnedValue, $this->modChecker->match($number));
    }

    /** @dataProvider getIncorrectData */
    public function testCheckedReturnedValueByIncorrectData(int $number, string|int $returnedValue): void {
        $this->assertNotEquals($returnedValue, $this->modChecker->match($number));
    }

    private function getCorrectData(): array {
        return [
            [3, 'Tom'],
            [5, 'Ula'],
            [15, 'TomUla'],
            [4, 4]
        ];
    }

    private function getIncorrectData(): array {
        return [
            [3, 'Dawid'],
            [5, 'Antek'],
            [15, 'UlaTom'],
            [4, 5]
        ];
    }
}